FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
   gcc \
   g++ \
   && rm -rf /var/lib/apt/lists/*


COPY requirements_server.txt .
RUN pip install --no-cache-dir -r requirements_server.txt 


COPY model/ ./model/
COPY utils/ ./utils/
COPY server ./server/
COPY api ./api/

EXPOSE 8000


CMD ["uvicorn", "api.server_api:app","--host", "0.0.0.0", "--port", "8000", "--workers", "1"]